import "../styles/reset.css"
import "../styles/viables.css"
import "../styles/basic.css"
import "../styles/pages/dialog.css"
import "../styles/components/button.css"
import "../styles/components/dropdown.css"
import "../styles/components/statusBar.css"
import "../styles/components/headerCommandBar.css"
import "../styles/components/link.css"
import "../styles/components/customChart.css"
import "../styles/components/contentContainer.css"
import "../styles/components/table.css"
import "../styles/components/footerNavigationCommandBar.css"
import "../styles/components/messageDialog.css"
import "../styles/components/isVisible.css"

export function initDialogStyles(){}